using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Lexer
{
    public static class ReservedWords
    {
        public static string[] Words = {
            "across",
            "agent",
            "alias",
            "all",
            "and",
            "as",
            "assign",
            "attribute",
            "BIT",
            "BOOLEAN",
            "CHARACTER",
            "check",
            "class",
            "convert",
            "create",
            "creation",
            "Current",
            "debug",
            "deferred",
            "do",
            "DOUBLE",
            "else",
            "elseif",
            "end",
            "ensure",
            "expanded",
            "export",
            "external",
            "False",
            "feature",
            "from",
            "frozen",
            "if",
            "implies",
            "indexing",
            "infix",
            "inherit",
            "inspect",
            "INTEGER",
            "invariant",
            "is",
            "like",
            "local",
            "loop",
            "NONE",
            "not",
            "note",
            "obsolete",
            "old",
            "once",
            "only",
            "or",
            "POINTER",
            "Precursor",
            "prefix",
            "REAL",
            "redefine",
            "rename",
            "require",
            "rescue",
            "Result",
            "retry",
            "select",
            "separate",
            "STRING",
            "strip",
            "then",
            "True",
            "TUPLE",
            "undefine",
            "unique",
            "until",
            "variant",
            "Void",
            "when",
            "xor"};

        public static string[] Operators =
        {
            "not",
            "+",
            "-",
            "*",
            "/",
            "//",
            "\\",
            "^",
            "..",
            "<",
            ">",
            "<=",
            ">=",
            "and",
            "or",
            "xor",
            "and then",
            "or else",
            "implies",
            ":=",
            "=",
            "/=",
            "~",
            "/~"
        };

        public static Dictionary<string, int> OpPriority = new Dictionary<string, int>{
            { "not", 10},
            { "+", 20},
            { "-", 30 },
            { "*", 40 },
            { "/", 50 },
            { "//", 60 },
            { "\\", 70 },
            { "^", 80 },
            { "..", 90 },
            { "<", 100 },
            { ">", 110 },
            { "<=", 120 },
            { ">=", 130 },
            { "xor", 140 },
            { "or", 150 },
            { "and", 160 },
            { "and then", 170 },
            { "or else", 180 },
            { "implies", 190 },
            { ":=", 200 },
            { "=", 210 },
            { "/=", 220 },
            { "~", 230 },
            { "/~", 240 }

        };
    }
}
