using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Lexer
{
    public static class ReservedWords
    {
        public static string[] Words = {
            "across",
            "agent",
            "alias",
            "all",
            "and",
            "as",
            "assign",
            "attribute",
            "BIT",
            "BOOLEAN",
            "CHARACTER",
            "check",
            "class",
            "convert",
            "create",
            "creation",
            "Current",
            "debug",
            "deferred",
            "do",
            "DOUBLE",
            "else",
            "elseif",
            "end",
            "ensure",
            "expanded",
            "export",
            "external",
            "False",
            "feature",
            "from",
            "frozen",
            "if",
            "implies",
            "indexing",
            "infix",
            "inherit",
            "inspect",
            "INTEGER",
            "invariant",
            "is",
            "like",
            "local",
            "loop",
            "NONE",
            "not",
            "note",
            "obsolete",
            "old",
            "once",
            "only",
            "or",
            "POINTER",
            "Precursor",
            "prefix",
            "REAL",
            "redefine",
            "rename",
            "require",
            "rescue",
            "Result",
            "retry",
            "select",
            "separate",
            "STRING",
            "strip",
            "then",
            "True",
            "TUPLE",
            "undefine",
            "unique",
            "until",
            "variant",
            "Void",
            "when",
            "xor"};
    }
}
